### PR TITLE
fix: example in README.md did not work

### PR DESCRIPTION
**Pull request by hanshuebner**

### CODE REVIEW

**Comment by Tieske** [comment]
This was a recent change. Did you try this against the master branch? It hasn’t been released probably

**Comment by hanshuebner** [comment]
Yes, this fixes the README.md file on the master branch.

**Comment by Tieske** [comment]
just tested, works for me? Considering your response;

> Yes, this fixes the README.md file on the master branch.

I'm wondering whether we're on the same page here; install from the main branch, by doing `luarocks make` from the repo. And then run the test code from the readme. That works for me.

**Comment by hanshuebner** [comment]
Ah, I get it now!  Sorry for the noise...

**Pull request closed without merging**
